// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app.sql

package queries

import (
	"context"
)

const appSettingsExist = `-- name: AppSettingsExist :one
SELECT EXISTS (SELECT 1 FROM app_settings WHERE id = TRUE)::boolean AS exists
`

func (q *Queries) AppSettingsExist(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, appSettingsExist)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createAppSettings = `-- name: CreateAppSettings :one
INSERT INTO app_settings (id, household_name, default_currency)
VALUES (TRUE, $1, 'CNY')
RETURNING id, household_name, default_currency, initialized_at, created_at, updated_at
`

func (q *Queries) CreateAppSettings(ctx context.Context, householdName string) (AppSetting, error) {
	row := q.db.QueryRow(ctx, createAppSettings, householdName)
	var i AppSetting
	err := row.Scan(
		&i.ID,
		&i.HouseholdName,
		&i.DefaultCurrency,
		&i.InitializedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppSettings = `-- name: GetAppSettings :one
SELECT id, household_name, default_currency, initialized_at, created_at, updated_at
FROM app_settings
WHERE id = TRUE
`

func (q *Queries) GetAppSettings(ctx context.Context) (AppSetting, error) {
	row := q.db.QueryRow(ctx, getAppSettings)
	var i AppSetting
	err := row.Scan(
		&i.ID,
		&i.HouseholdName,
		&i.DefaultCurrency,
		&i.InitializedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
