// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budgets.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const copyPreviousBudgets = `-- name: CopyPreviousBudgets :one
WITH inserted AS (
    INSERT INTO budgets (month, category_id, amount_cents)
    SELECT $1::text, b.category_id, b.amount_cents
    FROM budgets b
    JOIN categories c ON c.id = b.category_id
    WHERE b.month = $2
      AND c.active = TRUE
      AND c.type = 'expense'
    ON CONFLICT (month, category_id) DO NOTHING
    RETURNING id
)
SELECT count(*)::bigint AS copied_count
FROM inserted
`

type CopyPreviousBudgetsParams struct {
	TargetMonth string
	SourceMonth string
}

func (q *Queries) CopyPreviousBudgets(ctx context.Context, arg CopyPreviousBudgetsParams) (int64, error) {
	row := q.db.QueryRow(ctx, copyPreviousBudgets, arg.TargetMonth, arg.SourceMonth)
	var copied_count int64
	err := row.Scan(&copied_count)
	return copied_count, err
}

const listBudgetsByMonth = `-- name: ListBudgetsByMonth :many
SELECT id, month, category_id, amount_cents, created_at, updated_at
FROM budgets
WHERE month = $1
ORDER BY category_id
`

func (q *Queries) ListBudgetsByMonth(ctx context.Context, month string) ([]Budget, error) {
	rows, err := q.db.Query(ctx, listBudgetsByMonth, month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Budget
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.Month,
			&i.CategoryID,
			&i.AmountCents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonthlyBudgetSpending = `-- name: ListMonthlyBudgetSpending :many
SELECT
    t.category_id,
    COALESCE(SUM(t.amount_cents), 0)::bigint AS spent_cents
FROM transactions t
WHERE t.type = 'expense'
  AND t.transaction_date >= $1
  AND t.transaction_date < $2
GROUP BY t.category_id
`

type ListMonthlyBudgetSpendingParams struct {
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

type ListMonthlyBudgetSpendingRow struct {
	CategoryID pgtype.UUID
	SpentCents int64
}

func (q *Queries) ListMonthlyBudgetSpending(ctx context.Context, arg ListMonthlyBudgetSpendingParams) ([]ListMonthlyBudgetSpendingRow, error) {
	rows, err := q.db.Query(ctx, listMonthlyBudgetSpending, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMonthlyBudgetSpendingRow
	for rows.Next() {
		var i ListMonthlyBudgetSpendingRow
		if err := rows.Scan(&i.CategoryID, &i.SpentCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBudget = `-- name: UpsertBudget :one
INSERT INTO budgets (month, category_id, amount_cents)
VALUES ($1, $2, $3)
ON CONFLICT (month, category_id)
DO UPDATE SET amount_cents = EXCLUDED.amount_cents, updated_at = now()
RETURNING id, month, category_id, amount_cents, created_at, updated_at
`

type UpsertBudgetParams struct {
	Month       string
	CategoryID  pgtype.UUID
	AmountCents int64
}

func (q *Queries) UpsertBudget(ctx context.Context, arg UpsertBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, upsertBudget, arg.Month, arg.CategoryID, arg.AmountCents)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.Month,
		&i.CategoryID,
		&i.AmountCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
