// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package queries

import (
	"context"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, type, icon_key, color_key, sort_order, active, system_default)
VALUES ($1, $2, $3, $4, $5, TRUE, $6)
RETURNING id, name, type, icon_key, color_key, sort_order, active, system_default, created_at, updated_at
`

type CreateCategoryParams struct {
	Name          string
	Type          string
	IconKey       string
	ColorKey      string
	SortOrder     int32
	SystemDefault bool
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Name,
		arg.Type,
		arg.IconKey,
		arg.ColorKey,
		arg.SortOrder,
		arg.SystemDefault,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.IconKey,
		&i.ColorKey,
		&i.SortOrder,
		&i.Active,
		&i.SystemDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveCategories = `-- name: ListActiveCategories :many
SELECT id, name, type, icon_key, color_key, sort_order, active, system_default, created_at, updated_at
FROM categories
WHERE active = TRUE
ORDER BY type, sort_order, name
`

func (q *Queries) ListActiveCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listActiveCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.IconKey,
			&i.ColorKey,
			&i.SortOrder,
			&i.Active,
			&i.SystemDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
