// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMember = `-- name: CreateMember :one
INSERT INTO members (name, pin_hash, role, active)
VALUES ($1, $2, $3, TRUE)
RETURNING id, name, pin_hash, role, active, created_at, updated_at
`

type CreateMemberParams struct {
	Name    string
	PinHash string
	Role    string
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember, arg.Name, arg.PinHash, arg.Role)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PinHash,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberByID = `-- name: GetMemberByID :one
SELECT id, name, pin_hash, role, active, created_at, updated_at
FROM members
WHERE id = $1
`

func (q *Queries) GetMemberByID(ctx context.Context, id pgtype.UUID) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByID, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PinHash,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveLoginMembers = `-- name: ListActiveLoginMembers :many
SELECT id, name
FROM members
WHERE active = TRUE
ORDER BY lower(name)
`

type ListActiveLoginMembersRow struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) ListActiveLoginMembers(ctx context.Context) ([]ListActiveLoginMembersRow, error) {
	rows, err := q.db.Query(ctx, listActiveLoginMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveLoginMembersRow
	for rows.Next() {
		var i ListActiveLoginMembersRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
