// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SchemaMigration struct {
	Version   int64
	AppliedAt pgtype.Timestamptz
}
