// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: overview.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMonthlyTotals = `-- name: GetMonthlyTotals :one
SELECT
    COALESCE(SUM(amount_cents) FILTER (WHERE type = 'income'), 0)::bigint AS income_cents,
    COALESCE(SUM(amount_cents) FILTER (WHERE type = 'expense'), 0)::bigint AS expense_cents
FROM transactions
WHERE transaction_date >= $1 AND transaction_date < $2
`

type GetMonthlyTotalsParams struct {
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

type GetMonthlyTotalsRow struct {
	IncomeCents  int64
	ExpenseCents int64
}

func (q *Queries) GetMonthlyTotals(ctx context.Context, arg GetMonthlyTotalsParams) (GetMonthlyTotalsRow, error) {
	row := q.db.QueryRow(ctx, getMonthlyTotals, arg.StartDate, arg.EndDate)
	var i GetMonthlyTotalsRow
	err := row.Scan(&i.IncomeCents, &i.ExpenseCents)
	return i, err
}

const listMonthlyExpenseCategoryTotals = `-- name: ListMonthlyExpenseCategoryTotals :many
SELECT
    c.id AS category_id,
    c.name AS category_name,
    c.icon_key AS category_icon_key,
    c.color_key AS category_color_key,
    COALESCE(SUM(t.amount_cents), 0)::bigint AS expense_cents
FROM transactions t
JOIN categories c ON c.id = t.category_id
WHERE t.type = 'expense' AND t.transaction_date >= $1 AND t.transaction_date < $2
GROUP BY c.id, c.name, c.icon_key, c.color_key
ORDER BY expense_cents DESC, c.name
`

type ListMonthlyExpenseCategoryTotalsParams struct {
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

type ListMonthlyExpenseCategoryTotalsRow struct {
	CategoryID       pgtype.UUID
	CategoryName     string
	CategoryIconKey  string
	CategoryColorKey string
	ExpenseCents     int64
}

func (q *Queries) ListMonthlyExpenseCategoryTotals(ctx context.Context, arg ListMonthlyExpenseCategoryTotalsParams) ([]ListMonthlyExpenseCategoryTotalsRow, error) {
	rows, err := q.db.Query(ctx, listMonthlyExpenseCategoryTotals, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMonthlyExpenseCategoryTotalsRow
	for rows.Next() {
		var i ListMonthlyExpenseCategoryTotalsRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryIconKey,
			&i.CategoryColorKey,
			&i.ExpenseCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
