// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (member_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, member_id, token_hash, expires_at, created_at
`

type CreateSessionParams struct {
	MemberID  pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.MemberID, arg.TokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM sessions
WHERE token_hash = $1
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT
    sessions.id,
    sessions.member_id,
    sessions.token_hash,
    sessions.expires_at,
    sessions.created_at,
    members.name AS member_name,
    members.role AS member_role,
    members.active AS member_active
FROM sessions
JOIN members ON members.id = sessions.member_id
WHERE sessions.token_hash = $1
`

type GetSessionByTokenHashRow struct {
	ID           pgtype.UUID
	MemberID     pgtype.UUID
	TokenHash    string
	ExpiresAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	MemberName   string
	MemberRole   string
	MemberActive bool
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.MemberName,
		&i.MemberRole,
		&i.MemberActive,
	)
	return i, err
}
