// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (type, amount_cents, category_id, member_id, transaction_date, note)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, type, amount_cents, category_id, member_id, transaction_date, note, created_at, updated_at
`

type CreateTransactionParams struct {
	Type            string
	AmountCents     int64
	CategoryID      pgtype.UUID
	MemberID        pgtype.UUID
	TransactionDate pgtype.Date
	Note            string
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.Type,
		arg.AmountCents,
		arg.CategoryID,
		arg.MemberID,
		arg.TransactionDate,
		arg.Note,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.AmountCents,
		&i.CategoryID,
		&i.MemberID,
		&i.TransactionDate,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTransaction, id)
	return err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, type, amount_cents, category_id, member_id, transaction_date, note, created_at, updated_at
FROM transactions
WHERE id = $1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.AmountCents,
		&i.CategoryID,
		&i.MemberID,
		&i.TransactionDate,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTransactionsByMonth = `-- name: ListTransactionsByMonth :many
SELECT
    t.id,
    t.type,
    t.amount_cents,
    t.transaction_date,
    t.note,
    t.created_at,
    t.updated_at,
    c.id AS category_id,
    c.name AS category_name,
    c.type AS category_type,
    c.icon_key AS category_icon_key,
    c.color_key AS category_color_key,
    m.id AS member_id,
    m.name AS member_name,
    m.role AS member_role
FROM transactions t
JOIN categories c ON c.id = t.category_id
JOIN members m ON m.id = t.member_id
WHERE t.transaction_date >= $1 AND t.transaction_date < $2
ORDER BY t.transaction_date DESC, t.created_at DESC
`

type ListTransactionsByMonthParams struct {
	StartDate pgtype.Date
	EndDate   pgtype.Date
}

type ListTransactionsByMonthRow struct {
	ID               pgtype.UUID
	Type             string
	AmountCents      int64
	TransactionDate  pgtype.Date
	Note             string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	CategoryID       pgtype.UUID
	CategoryName     string
	CategoryType     string
	CategoryIconKey  string
	CategoryColorKey string
	MemberID         pgtype.UUID
	MemberName       string
	MemberRole       string
}

func (q *Queries) ListTransactionsByMonth(ctx context.Context, arg ListTransactionsByMonthParams) ([]ListTransactionsByMonthRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByMonth, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsByMonthRow
	for rows.Next() {
		var i ListTransactionsByMonthRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.AmountCents,
			&i.TransactionDate,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryID,
			&i.CategoryName,
			&i.CategoryType,
			&i.CategoryIconKey,
			&i.CategoryColorKey,
			&i.MemberID,
			&i.MemberName,
			&i.MemberRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET
    type = $2,
    amount_cents = $3,
    category_id = $4,
    transaction_date = $5,
    note = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, type, amount_cents, category_id, member_id, transaction_date, note, created_at, updated_at
`

type UpdateTransactionParams struct {
	ID              pgtype.UUID
	Type            string
	AmountCents     int64
	CategoryID      pgtype.UUID
	TransactionDate pgtype.Date
	Note            string
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.Type,
		arg.AmountCents,
		arg.CategoryID,
		arg.TransactionDate,
		arg.Note,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.AmountCents,
		&i.CategoryID,
		&i.MemberID,
		&i.TransactionDate,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
